import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Benjamin',
      email: 'benrc84@hotmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Pabel',
      email: 'usuario@ejemplo.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],

  products: [
    {
      // _id: '1',
      name: 'Cadena oro',
      slug: 'cadena-oro',
      categoria: 'cadenas',
      img: 'https://www.joyeriasbizzarro.com/media/catalog/product/1/5/150gaxpde1360p-x3.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
      precio: 500,
      cantidad: 8,
      Marca: 'Cartier',
      rating: 5,
      numReviews: 10,
      Descripcion: 'cadena de oro de 12k',
    },
    {
      // _id: '2',
      name: 'Anillo de perlas',
      slug: 'anillo-perlas',
      categoria: 'anillo',
      img: 'https://www.joyeriasbizzarro.com/media/catalog/product/a/n/anillo-amarillo-bbs-51-an_x3.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
      precio: 1500.0,
      cantidad: 4,
      Marca: 'Harry Winston',
      rating: 5,
      numReviews: 6,
      Descripcion: 'anillo con perlas negras oro de 24k',
    },
    {
      // _id: '3',
      name: 'Aritos baño de oro',
      slug: 'aritos-oro',
      categoria: 'Aritos',
      img: 'https://www.joyeriasbizzarro.com/media/catalog/product/a/r/aretes-sele00002-x1.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
      precio: 200,
      cantidad: 5,
      Marca: 'Cartier',
      rating: 3.5,
      numReviews: 2,
      Descripcion: 'aritos con baño de oro de 10k',
    },
    {
      // _id: '4',
      name: 'Aritos plata',
      slug: 'aritos-plata',
      categoria: 'Aritos',
      img: 'https://www.joyeriasbizzarro.com/media/catalog/product/a/r/aretes-kde00027-y-x1.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
      precio: 200,
      cantidad: 10,
      Marca: 'Cartier',
      rating: 3.5,
      numReviews: 2,
      Descripcion: 'aritos de plata',
    },
    {
      // _id: '5',
      name: 'Accesorios',
      slug: 'accesorios',
      categoria: 'Varios',
      img: 'https://www.joyeriasbizzarro.com/media/catalog/product/j/g/jgo-mas147-x1.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
      precio: 2500,
      cantidad: 0,
      Marca: 'Cartier',
      rating: 5,
      numReviews: 10,
      Descripcion: 'Accesorios de oro, anillos, cadenas, dijes',
    },
    {
      // _id: '6',
      name: 'Cadena Diamantes',
      slug: 'cadena-diamantes',
      categoria: 'cadenas',
      img: 'https://www.joyeriasbizzarro.com/media/catalog/product/d/i/dije-amarillo-12631sru4yv_x1.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
      precio: 5000,
      cantidad: 5,
      Marca: 'Cartier',
      rating: 3.5,
      numReviews: 2,
      Descripcion: 'Cadena de diamantes y aritos',
    },
    {
      // _id: '7',
      name: 'Pulsera Cuarzo',
      slug: 'pulsera-cuarzo',
      categoria: 'Pulsera',
      img: 'https://www.joyeriasbizzarro.com/media/catalog/product/p/u/pulsera-ekbl00001-y-x1.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
      precio: 3500,
      cantidad: 5,
      Marca: 'Cartier',
      rating: 3.5,
      numReviews: 2,
      Descripcion: 'Pulsera de Cuarzo y aritos',
    },
    {
      // _id: '8',
      name: 'Anillo Imperial',
      slug: 'anillo-imperial',
      categoria: 'Anillos',
      img: 'https://www.joyeriasbizzarro.com/media/catalog/product/a/n/anillo-ms12r4865w-76-x2.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
      precio: 2000,
      cantidad: 5,
      Marca: 'Cartier',
      rating: 3.5,
      numReviews: 2,
      Descripcion: 'Anillo de forma imperial ',
    },

    {
      // _id: '8',
      name: 'Cadena Plata',
      slug: 'cadena-plata',
      categoria: 'cadena',
      img: 'https://www.joyeriasbizzarro.com/media/catalog/product/c/a/cadena-065gaxpde0140p-x1_1.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
      precio: 2000,
      cantidad: 5,
      Marca: 'Cartier',
      rating: 3.5,
      numReviews: 2,
      Descripcion: 'cadena plata ',
    },
    {
      // _id: '8',
      name: 'cadena',
      slug: 'caneda',
      categoria: 'cadena',
      img: 'https://www.joyeriasbizzarro.com/media/catalog/product/c/a/cadena-065gaxpde0140p-x1_1.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
      precio: 2000,
      cantidad: 5,
      Marca: 'Cartier',
      rating: 3.5,
      numReviews: 2,
      Descripcion: 'cadena plata ',
    },
  ],
};
console.log(data);

export default data;
